apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: verl-inference-scheduler
  namespace: default
spec:
  rayVersion: 2.52.0
  headGroupSpec:
    rayStartParams:
      num-cpus: '0'
      num-gpus: '0'
      dashboard-host: 0.0.0.0
    template:
      metadata:
        annotations:
          networking.gke.io/default-interface: eth0
      spec:
        imagePullSecrets:
        - name: artifact-registry-secret
        containers:
        - name: ray-head
          image: verlai/verl:vllm011.latest
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
            name: gcs
            protocol: TCP
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 10001
            name: client
            protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 16Gi
            requests:
              cpu: '4'
              memory: 16Gi
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-tmp
          - mountPath: /home/ray/data
            name: data
        volumes:
        - name: ray-tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
  workerGroupSpecs:
  - replicas: 2
    minReplicas: 2
    maxReplicas: 2
    groupName: gpu-group
    rayStartParams:
      num-gpus: '8'
    template:
      spec:
        imagePullSecrets:
        - name: artifact-registry-secret
        containers:
        - name: ray-worker
          image: verlai/verl:vllm011.latest
          imagePullPolicy: Always
          env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-secret
                key: hf_api_token
          - name: LD_LIBRARY_PATH
            value: /usr/local/nvidia/lib64
          resources:
            limits:
              cpu: '64'
              memory: 1024Gi
              nvidia.com/gpu: '8'
            requests:
              cpu: '64'
              memory: 1024Gi
              nvidia.com/gpu: '8'
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-tmp
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /usr/local/nvidia
            name: nvidia
          - mountPath: /usr/local/gib
            name: gib
        volumes:
        - name: ray-tmp
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
        - name: nvidia
          hostPath:
            path: /home/kubernetes/bin/nvidia
        - name: gib
          hostPath:
            path: /home/kubernetes/bin/gib
      metadata:
        annotations:
          networking.gke.io/default-interface: eth0
          networking.gke.io/interfaces: "[\n  {\"interfaceName\":\"eth0\",\"network\"\n            :\"default\"},\n  {\"interfaceName\":\"eth1\",\"network\":\"gvnic-1\"\n            },\n  {\"interfaceName\":\"eth2\",\"network\":\"rdma-0\"},\n  {\"interfaceName\"\n            :\"eth3\",\"network\":\"rdma-1\"},\n  {\"interfaceName\":\"eth4\",\"network\"\n            :\"rdma-2\"},\n  {\"interfaceName\":\"eth5\",\"network\":\"rdma-3\"},\n  {\"interfaceName\":\"eth6\",\"network\":\"rdma-4\"},\n  {\"interfaceName\"\n            :\"eth7\",\"network\":\"rdma-5\"},\n  {\"interfaceName\":\"eth8\",\"network\"\n            :\"rdma-6\"},\n  {\"interfaceName\":\"eth9\",\"network\":\"rdma-7\"}\n            ]\n"
